### PR TITLE
create 'jxlint-maven' project

### PR DESCRIPTION
**Pull request by jmini**
Fix for #12

### CODE REVIEW

**Comment by jmini** [comment]
As discussed on #12 and in #15 this version can be improved, but it handles all the configurations possibilities and works.

When installed in a local maven repo (see #14), it can be tested with the projects `jxlint-impl-maven-plugin` and `txtlinter-maven-plugin` (described on [this page](https://jmini.github.io/jxlint-experiments/)). Take the version from branch [test_v2.0.0](https://github.com/jmini/jxlint-experiments/tree/test_v2.0.0)

I hope you can review it and test if the code is correctly formatted.

**Comment by selesse** [comment]
I'll take a closer look at this in the next few days. I want to run some tests on my end first. At a quick glance, it looks good!

**Comment by jmini** [comment]
Take your time to review it. I have mentioned how I have tested it.

As I explained in #15, I think that the code can be improved, but we can do this in a next step.

I would also appreciate if you can run your code formatter on the code. I did not have the time to install any other new tool and I currently work with what I know.

**Comment by selesse** [comment]
Merged in 50da25d.

**Pull request closed without merging**
